import type { Metadata } from 'next'
import '../../css/global.css'
import { Inria_Sans } from 'next/font/google'
import Header from './_components/_Header/Header'

const inriaSans = Inria_Sans({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inriaSans.className}>
                <Header />

                {children}
            </body>
        </html>
    )
}
